# sh exec-on-changes.sh  ${{ inputs.command }} >> $GITHUB_OUTPUT

name: 'Execute on changes'
description: 'If there are any changed files in the last commit under the <path> execute the <command>.'
inputs:
  path:
    description: 'Path where find changes in files'
    required: true
  command:
    description: 'Command to execute if changes in files where found.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Execute on changes
      shell: bash
      env:
        COMMAND: ${{ inputs.command }}
        PATH: ${{ inputs.path }} 
      run: |
        # Get the list of files changed in the last commit under the specified folder
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD -- "$PATH")

        # Check if there are any changed files
        if [ -n "$CHANGED_FILES" ]; then
          echo "Changes detected in the following files:"
          echo "$CHANGED_FILES"
          
          # Execute the specified command
          echo "Executing command: $COMMAND"
          $COMMAND
        else
          echo "No changes detected in the folder: $PATH"
        fi


